#! /home/david/.venvs/neomutt/bin/python
# vim: set fileencoding=utf8 :

# • the unusual shebang is because the 'xerox' and
#   'html2text' modules are installed in a virtual
#   environment (~/.venvs/neomutt)
# • if the script is run using the python excecutable
#   from that virtual environment it automatically
#   finds those modules
# • the modules are installed in the virtual
#   environment in a subdirectory specific to the
#   version of python in use at the time the module
#   was installed
# • when the system python is upgraded to a new
#   version, e.g., python3 3.12→3.13, this script
#   will be unable to locate the modules, and will
#   fail with a ModulNotFound error for 'html2text'
# • the solution is to delete and re-create the
#   virtual environment and reinstall into it the
#   'xerox' and 'html2text' modules
# • use these commands:
#     rm -fr ~/.venvs/neomutt
#     python3 -m venv ~/.venvs/neomutt
#     ~/.venvs/neomutt/bin/python -m pip install html2text xerox

# pyright: reportAny=false
# pyright: reportAttributeAccessIssue=false
# pyright: reportMissingParameterType=false
# pyright: reportUnknownArgumentType=false
# pyright: reportUnknownMemberType=false
# pyright: reportUnknownParameterType=false
# pyright: reportUnknownVariableType=false
# pylint: disable=invalid-name

# module docstring    {{{1
"""script to send email content to clipboard

This script reads an email from stdin, extracts the
content/payload as plain text, and sends it to the system
clipboard.

Copyright: David Nebauer, 2023-01-29
License: GPL-3+
"""

# import    {{{1

import argparse
import io
import logging as log
import re
import sys
import textwrap
from email import message_from_string, policy
from email.message import EmailMessage, Message

import html2text

# xerox module is part of a virtual environment (see shebang)
# • although linter cannot find it, python finds it at runtime
import xerox  # type: ignore[import-not-found] # noqa: E402


class ContentToClipboard:  # {{{1
    # class docstring    {{{2
    """send content to clipboard as plain text

    assumes:
    • email is supplied via stdin

    usage:

    sendclip = ContentToClipboard()
    sendclip.process_args()
    sendclip.create_email_object()
    sendclip.extract_content()
    sendclip.send_to_clipboard()
    """

    def __init__(self) -> None:
        """initialise variables"""
        # configure logging
        log.basicConfig(format="%(message)s")

        # email object
        self._email: EmailMessage[str, str] | None = None

        # email content
        self._content: str | None = None

    @staticmethod
    def _abort(msg: str) -> None:  # {{{2
        """display error and exit"""
        log.error(msg)
        sys.exit(msg)

    @staticmethod
    def _tidy_content(content) -> str:  # {{{2
        """tidy up content"""
        # first, ensure content is a string
        # • in case EmailMessage.get_content() returned
        #   something funky instead of a string
        text: str = ""
        if isinstance(content, bytes):
            text = content.decode()
        elif isinstance(content, Message):
            text = content.as_string()
        elif isinstance(content, str):
            text = content
        else:
            text = str(content, errors="replace")
        # have no more than 1 empty line at a time
        text = re.sub(r"(\n\s*)+\n", "\n\n", text)
        # remove terminal spaces from lines
        text = "\n".join(line.strip() for line in text.splitlines())
        return text

    @staticmethod
    def process_args() -> None:  # {{{2
        """print help if requested"""
        description: str = textwrap.dedent(
            text="""\
        script to send email content to clipboard as plain text

        This script reads an email from stdin, extracts any
        text/plain, text/markdown, and text/html content as
        plain text and sends it to the system clipboard.
        """
        )
        _ = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description=description,
        ).parse_args()

    def create_email_object(self) -> None:  # {{{2
        """create email object from stdin"""
        # save stdin to string
        # - ignore UnicodeDecodeErrors from sys.stdin.readlines
        if isinstance(sys.stdin, io.TextIOWrapper):
            sys.stdin.reconfigure(encoding="utf-8", errors="ignore")
        if sys.stdin.isatty():
            self._abort(msg="No data has been piped into script")
        lines: list[str] = sys.stdin.readlines()
        data: str = "".join(lines)
        # create email object
        # • default policy forces creation of EmailMessage instead of Message
        self._email = message_from_string(data, policy=policy.default)

    def extract_content(self) -> None:  # {{{2
        """extract email content as plain text
        • handles multipart and nested multipart messages

        return:
        • all text/html content from all parts (as plaintext string)
        """
        msg = self._email
        sep = "\n\n\n"
        text = ""
        # deal with message extraction failure
        if msg is None:
            raise ValueError("No message found")
        # message should be an EmailMessage
        elif isinstance(msg, EmailMessage):
            plain_text_types = ["text/plain", "text/markdown"]
            html_text_types = ["text/html"]
            # iterate through message parts
            # • walk() iterates through all parts depth-first
            # • walk() handles simple, non-multipart messages
            for part in msg.walk():
                # 'get_content_disposition()' returns 'inline',
                # 'attachment' or NoneType
                content_disposition = part.get_content_disposition()
                if content_disposition is None:
                    content_disposition = "inline"
                content_disposition = content_disposition.capitalize()
                content_type = part.get_content_type()
                # ignore 'packaging', that is, multipart parts
                if content_type.startswith("multipart/"):
                    continue
                # skip attachments
                if content_disposition == "Attachment":
                    header = f"*** <Attachment ({content_type})>"
                    header += " -- skipping ***"
                    text += header + sep
                    continue
                # deal with remaining message parts
                # • stringify content in case 'get_content_type' returned
                #   a bytes object, as these can confuse 'html2text' and
                #   cause string concatenation problems
                if content_type in plain_text_types:
                    content = part.get_content()
                    content = self._tidy_content(content)
                    header = f"*** <{content_disposition}"
                    header += f" ({content_type})> ***"
                    text += header + sep + content + sep
                elif content_type in html_text_types:
                    content = part.get_content()
                    content = html2text.html2text(content)
                    content = self._tidy_content(content)
                    header = f"*** <{content_disposition}"
                    header += f" ({content_type})> ***"
                    text += header + sep + content + sep
                else:
                    header = f"*** <{content_disposition} ({content_type})>"
                    header += " -- skipping ***"
                    text += header + sep
        # handle edge cases where value is not an email object
        # • so far we handle 'bytes' and 'str' types
        elif isinstance(msg, bytes):
            try:
                # if 'msg.decode()' then 'errors' defaults to 'strict'
                # • script works in terminal but *not* in neomutt (no output)
                # if 'msg.decode(errors="ignore")'
                # • script works in terminal *and* in neomutt
                # • but undecodable bytes are silently dropped from output
                # experimenting with Latin-1 encodingto see if it reduces
                # decoding errors, that is, dropped bytes
                content = msg.decode(encoding="latin-1", errors="ignore")
                header = "*** <bytes> ***"
                text += header + sep + content + "\n\n"
            except ValueError as err:
                errmsg = getattr(err, "message", str(err))
                header = f"*** <bytes> -- decode error: {errmsg} ***"
                text += header + sep
        elif isinstance(msg, str):
            content = msg
            header = "*** <str> ***"
            text += header + sep + content + "\n\n"
        else:
            raise ValueError(f"Unknown message format {str(type(msg))}")
        self._content = text

    def send_to_clipboard(self):  # {{{2
        """send extracted plaintext content to clipboard
        use xerox.copy():
        • homepage is https://github.com/adityarathod/xerox
        • packaged to install with pip (see https://pypi.org/project/xerox/)
        before using xerox.copy() tried:
        • pyperclip.copy(content)
          - failed silently
        • tkinter.Tk.clipboard_append(content)
          - if used 'mainloop' it worked but that showed the main window,
            which halted execution until the user dismissed it
          - a workaround was supposedly to use 'update' instead of
            'mainloop', but that failed silently
        • pandas.DataFrame([content]).to_clipboard(index=False, header=False)
          - works successfully, but wraps the content in double quotes
          - could not find a workaround to prevent this
        """
        xerox.copy(self._content)


# }}}1


def main():
    """script execution starts here"""
    sendclip = ContentToClipboard()
    sendclip.process_args()
    sendclip.create_email_object()
    sendclip.extract_content()
    sendclip.send_to_clipboard()


if __name__ == "__main__":
    main()

# vim:fdm=marker:
