#!/bin/sh

# bash-define: Allows thesaurus lookups from the terminal.
# Requires moby-thesaurus.
# Necessary because zsh does not load 'thesaurus' function defined in the file
# 'dict' since it assumes one function per file, having the same name as the
# file.
# Call file and function 'thes' rather than 'thesaurus' to avoid future
# conflict with (currently non-loading) 'thesaurus' function in 'dict' file.
#

thes() {
    dict ${1} moby-thesaurus
}

# Tab Completion. Completes words if "WORDLIST" exists.
# Otherwise just completes options.
if [[ "${SHELL}" =~ '.*zsh$' || ${SHELL} =~ '.*bash$' ]]; then
    [ -f /usr/share/dict/words ] && \
    WORDLIST="/usr/share/dict/words"
    [ -f /usr/share/dict/cracklib-small ] && \
    WORDLIST="/usr/share/dict/cracklib-small"

    _thes() {
        COMPREPLY=( $(grep -h "^${COMP_WORDS[COMP_CWORD]}" ${WORDLIST}) )
        return 0
    } && complete -F _thes thes
fi
