#!/bin/sh

# adapted from https://github.com/anufrievroman/Neomutt-File-Picker
# - note the  in the sed command below is created in vim
#   with 'Ctrl-v Ctrl-v' -- it is a control character and
#   not two characters '^' and 'V' as in the repository file
# - it is assumed the default editor mode/menu mapping of
#   Ctrl-v (aka ^V) to the <quote-char> function is in place

tmpfile=$HOME/.cache/neomutt/picker-cache

if \[ -z "$1" \]; then
    ranger --choosefiles $tmpfile &&
    sed -i 's/ / /g' $tmpfile &&
    echo "$(awk 'BEGIN {printf "%s", "push "} {printf "%s", "<attach-file>\""$0"\"<enter>"}'  $tmpfile)" > $tmpfile
elif \[ $1 == "clean" \]; then
    rm $tmpfile
fi
